package net.justonedev;

/**
 * Provides all known testcases for this task.
 *
 * @author uwwfh
 */
public final class Testcases {
    /**
     * All test cases, encoded as a single string. Impressive, right?
     */
    public static final String TESTS = """
name:§FUNCTIONAL§Basic:§change-priority%ncomment:§Tests§if§change-priority§command§basically§behaves§as§expected%nargs:%n--%n#setup%n>add§be
d%nadded§1:§bed%n>add§blanket%nadded§2:§blanket%n>add§pillow%nadded§3:§pillow%n>add§table§HI%nadded§4:§table%n>add§tv§MD%nadded§5:§tv%n>add§
phone§LO%nadded§6:§phone%n#%n#%n#%n#test§change-priority%n>change-priority§1§HI#§§§§§§§no§prio§->§high%nchanged§bed§to§HI%n>change-priority§
1§HI#§§§§§§§change§high§->§high%nchanged§bed§to§HI%n>change-priority§2§MD#§§§§§§§no§prio§->§medium%nchanged§blanket§to§MD%n>change-priority§
2§MD#§§§§§§§change§medium§->§medium%nchanged§blanket§to§MD%n>change-priority§3§LO#§§§§§§§no§prio§->§low%nchanged§pillow§to§LO%n>change-prior
ity§3§LO#§§§§§§§change§low§->§low%nchanged§pillow§to§LO%n>change-priority§4§MD#§§§§§§§preset§high§->§medium%nchanged§table§to§MD%n>change-pr
iority§4§LO#§§§§§§§change§medium§->§low%nchanged§table§to§LO%n>change-priority§4§HI#§§§§§§§change§low§->§high%nchanged§table§to§HI%n>change-
priority§5§HI#§§§§§§§preset§medium§->§high%nchanged§tv§to§HI%n>change-priority§5§LO#§§§§§§§change§high§->§low%nchanged§tv§to§LO%n>change-pri
ority§5§MD#§§§§§§§change§low§->§medium%nchanged§tv§to§MD%n>change-priority§6§LO#§§§§§§§preset§low§->§low%nchanged§phone§to§LO%n>change-prior
ity§6#§§§§§§§§§§low§->§no§prio%nchanged§phone§to§NONE%n>change-priority§5#§§§§§§§§§§medium§->§no§prio%nchanged§tv§to§NONE%n>change-priority§
4#§§§§§§§§§§high§->§no§prio%nchanged§table§to§NONE%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLING:§restore%ncomment:§Tests§if§the§parameters§are§pa
rsed§correctly,§no§working§model§expected%nargs:%n--%n>add§task%n!R!^(?!ERROR:§).*$%n>delete§1%n!R!^(?!ERROR:§).*$%n>restore%n!A!!R!^ERROR:§
.*%n>restore§1§1%n!A!!R!^ERROR:§.*%n>restore§task%n!A!!R!^ERROR:§.*%n>restore§1%n!R!^(?!ERROR:§).*$%n>quit%Tname:§FUNCTIONAL§Basic:§change-d
ate%ncomment:§Tests§if§change-date§command§basically§behaves§as§expected%nargs:%n--%n#setup%n>add§lamp%nadded§1:§lamp%n>add§chair§2020-04-01
%nadded§2:§chair%n#%n#%n#%n#test§change-date%n>change-date§1§2024-01-20#§§§§§§§no§date§->§random§date%nchanged§lamp§to§2024-01-20%n>change-d
ate§1§2024-01-20#§§§§§§§date§->§same§date%nchanged§lamp§to§2024-01-20%n>change-date§1§2083-10-10#§§§§§§§date§->§different§date%nchanged§lamp
§to§2083-10-10%n>change-date§2§3024-01-20#§§§§§§§preset§date§->§different§date%nchanged§chair§to§3024-01-20%n>change-date§2§3024-01-20#§§§§§
§§date§->§same§date%nchanged§chair§to§3024-01-20%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLING:§change-priority%ncomment:§Tests§if§the§parameters§
are§parsed§correctly,§no§working§model§expected%nargs:%n--%n>add§task%n!R!^(?!ERROR:§).*$%n>change-priority%n!A!!R!^ERROR:§.*%n>change-prior
ity§1§HI§HI%n!A!!R!^ERROR:§.*%n>change-priority§1§HIGH%n!A!!R!^ERROR:§.*%n>change-priority§1§MIDDLE%n!A!!R!^ERROR:§.*%n>change-priority§1§LO
W%n!A!!R!^ERROR:§.*%n>change-priority§1§1%n!A!!R!^ERROR:§.*%n>change-priority§1%n!R!^(?!ERROR:§).*$%n>change-priority§1§HI%n!R!^(?!ERROR:§).
*$%n>change-priority§1§MD%n!R!^(?!ERROR:§).*$%n>change-priority§1§LO%n!R!^(?!ERROR:§).*$%n>quit%Tname:§FUNCTIONAL§Basic:§find%ncomment:§Test
s§if§find§commands§basically§behaves§as§expected%nargs:%n--%n>find§nothing%n>add§task%nadded§1:§task%n>add§subtask%nadded§2:§subtask%n>add§s
ubsub%nadded§3:§subsub%n>add§find%nadded§4:§find%n>assign§3§2%nassigned§subsub§to§subtask%n>assign§2§1%nassigned§subtask§to§task%n>add§notSo
sub%nadded§5:§notSosub%n>assign§5§1%nassigned§notSosub§to§task%n>find§task%n-§[§]§task%n§§-§[§]§subtask%n§§§§-§[§]§subsub%n§§-§[§]§notSosub%
n>find§sub%n-§[§]§subtask%n§§-§[§]§subsub%n-§[§]§notSosub%n>find§find%n-§[§]§find%n>find§subtask%n-§[§]§subtask%n§§-§[§]§subsub%n>quit%Tname
:§FUNCTIONAL§ERROR§HANDLING:§before%ncomment:§Tests§if§the§parameters§are§parsed§correctly,§no§working§model§expected%nargs:%n--%n>before%n!
A!!R!^ERROR:§.*%n>before§2023-08-01§2023-08-01%n!A!!R!^ERROR:§.*%n>before§2023.08.01%n!A!!R!^ERROR:§.*%n>before§01-08-2023%n!A!!R!^ERROR:§.*
%n>before§23-08-01%n!A!!R!^ERROR:§.*%n>before§2023-09-31%n!A!!R!^ERROR:§.*%n>before§2023-13-01%n!A!!R!^ERROR:§.*%n>before§2023-00-01%n!A!!R!
^ERROR:§.*%n>before§2023-01-00%n!A!!R!^ERROR:§.*%n>before§2023-02-29%n!A!!R!^ERROR:§.*%n>before§2024-02-29%n>before§2023-08-01%n>before§0000
-01-01%n>before§9999-12-31%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLING:§between%ncomment:§Tests§if§the§parameters§are§parsed§correctly,§no§worki
ng§model§expected%nargs:%n--%n>between%n!A!!R!^ERROR:§.*%n>between§2023-07-31%n!A!!R!^ERROR:§.*%n>between§2023-07-31§2023-08-01§2023-08-01%n
!A!!R!^ERROR:§.*%n>between§2023.07.31§2023-08-01%n!A!!R!^ERROR:§.*%n>between§31-07-2023§2023-08-01%n!A!!R!^ERROR:§.*%n>between§23-07-31§2023
-08-01%n!A!!R!^ERROR:§.*%n>between§2023-09-31§2023-08-01%n!A!!R!^ERROR:§.*%n>between§2023-13-01§2023-08-02%n!A!!R!^ERROR:§.*%n>between§2023-
00-01§2023-08-03%n!A!!R!^ERROR:§.*%n>between§2023-01-00§2023-08-04%n!A!!R!^ERROR:§.*%n>between§2023-02-29§2023-08-05%n!A!!R!^ERROR:§.*%n>bet
ween§2023-07-31§2023.08.01%n!A!!R!^ERROR:§.*%n>between§2023-07-31§01-08-2023%n!A!!R!^ERROR:§.*%n>between§2023-07-31§23-08-01%n!A!!R!^ERROR:§
.*%n>between§2023-07-31§2023-09-31%n!A!!R!^ERROR:§.*%n>between§2023-07-31§2023-13-01%n!A!!R!^ERROR:§.*%n>between§2023-07-31§2023-00-01%n!A!!
R!^ERROR:§.*%n>between§2023-07-31§2023-01-00%n!A!!R!^ERROR:§.*%n>between§2023-07-31§2023-02-29%n!A!!R!^ERROR:§.*%n>between§2023-07-31§2023-0
8-01%n>between§2024-02-29§2024-08-06%n>between§2023-07-31§2024-02-29%n>between§2020-02-29§2024-02-29%n>between§2023-07-31§2023-07-31%n>betwe
en§9999-12-31§0000-01-01%n>between§0000-01-01§9999-12-31%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLING:§assign%ncomment:§Tests§if§the§parameters§a
re§parsed§correctly,§no§working§model§expected%nargs:%n--%n>add§task1%n!R!^(?!ERROR:§).*$%n>add§task2%n!R!^(?!ERROR:§).*$%n>add-list§list%n!
R!^(?!ERROR:§).*$%n>assign%n!A!!R!^ERROR:§.*%n>assign§2§1§whatever%n!A!!R!^ERROR:§.*%n>assign§2§list§whatever%n!A!!R!^ERROR:§.*%n>assign§lis
t§2%n!A!!R!^ERROR:§.*%n>assign§2§1%n!R!^(?!ERROR:§).*$%n>assign§1§list%n!R!^(?!ERROR:§).*$%n>quit%Tname:§FUNCTIONAL§Basic:§assign%ncomment:§
Tests§if§assign§command§basically§behaves§as§expected%nargs:%n--%n#§§§§§§§setup%n>add§one%nadded§1:§one%n>add§top%nadded§2:§top%n>add§jgl%na
dded§3:§jgl%n>add§mid%nadded§4:§mid%n>add§bot%nadded§5:§bot%n>add§sup%nadded§6:§sup%n>add-list§listOne%nadded§listOne%n>add-list§listTwo%nad
ded§listTwo%n#%n#%n#%n#§§§§§§§test§assign§for§tasks%n>assign§1§1%n!A!!R!^ERROR:§.*%n>assign§6§5%nassigned§sup§to§bot%n>assign§6§5%n!A!!R!^ER
ROR:§.*%n>assign§6§4%nassigned§sup§to§mid%n>assign§6§4%n!A!!R!^ERROR:§.*%n>assign§6§5%nassigned§sup§to§bot%n>assign§3§5%nassigned§jgl§to§bot
%n>assign§4§2%nassigned§mid§to§top%n>assign§5§2%nassigned§bot§to§top%n>assign§3§5%n!A!!R!^ERROR:§.*%n>assign§3§4%nassigned§jgl§to§mid%n#%n#%
n#%n#§§§§§§§test§assign§for§lists%n>assign§1§listOne%nassigned§one§to§listOne%n>assign§1§listTwo#§§§§§§§assign§to§multiple§lists%nassigned§o
ne§to§listTwo%n>assign§2§listTwo#§§§§§§§multiple§tasks§assigned§in§a§list%nassigned§top§to§listTwo%n>assign§3§listTwo#§§§§§§§deny§assigning§
subtask§because§upper§task§already§is§assigned%n!A!!R!^ERROR:§.*%n>assign§4§listTwo#§§§§§§§deny§assigning§subtask§because§upper§task§already
§is§assigned%n!A!!R!^ERROR:§.*%n>assign§5§listTwo#§§§§§§§deny§assigning§subtask§because§upper§task§already§is§assigned%n!A!!R!^ERROR:§.*%n>a
ssign§6§listTwo#§§§§§§§deny§assigning§subtask§because§upper§task§already§is§assigned%n!A!!R!^ERROR:§.*%n>assign§6§listOne#§§§§§§§assign§subt
ask§to§a§list§not§containing§upper§task%nassigned§sup§to§listOne%n>assign§3§listOne#§§§§§§§assign§subtask§to§a§list§not§containing§upper§tas
k%nassigned§jgl§to§listOne%n>assign§5§listOne#§§§§§§§assign§subtask§to§a§list§not§containing§upper§task%nassigned§bot§to§listOne%n>assign§4§
listOne#§§§§§§§assign§subtask§to§a§list§not§containing§upper§task%nassigned§mid§to§listOne%n>assign§3§listOne#§§§§§§§retry§assigning§task§al
ready§in§list%n!A!!R!^ERROR:§.*%n>assign§4§listOne#§§§§§§§retry§assigning§task§already§in§list%n!A!!R!^ERROR:§.*%n>assign§5§listOne#§§§§§§§r
etry§assigning§task§already§in§list%n!A!!R!^ERROR:§.*%n>assign§2§listOne#§§§§§§§add§top§level§task§to§list§containing§some§subtasks%nassigne
d§top§to§listOne%n>assign§6§listOne#§§§§§§§retry§assigning§task§already§in§list%n!A!!R!^ERROR:§.*%n>assign§2§listOne#§§§§§§§retry§assigning§
top§level§task%n!A!!R!^ERROR:§.*%n#%n#%n#%n#§§§§§§§misc%n>assign§1§2#§§§§§§§§§§§§§assign§task§to§task§when§both§in§list%nassigned§one§to§top
%n>add§newTask%nadded§7:§newTask%n>assign§7§2#§§§§§§§§§§§§§assign§task§to§task§when§only§upper§task§in§list%nassigned§newTask§to§top%n>delet
e§1%ndeleted§one§and§0§subtasks%n>assign§2§1%n!A!!R!^ERROR:§.*%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLING:§show%ncomment:§Tests§if§the§paramete
rs§are§parsed§correctly,§no§working§model§expected%nargs:%n--%n>add§task%n!R!^(?!ERROR:§).*$%n>show%n!A!!R!^ERROR:§.*%n>show§1§1%n!A!!R!^ERR
OR:§.*%n>show§task%n!A!!R!^ERROR:§.*%n>show§1%n!R!^(?!ERROR:§).*$%n>quit%Tname:§FUNCTIONAL§Mixed:§restore;assign;todo;list%ncomment:§Tests§i
f§restore§command§basically§behaves§as§expected%nargs:%n--%n#setup%n>add§slicedBeef%nadded§1:§slicedBeef%n>add§slicedLamb%nadded§2:§slicedLa
mb%n>add§hotpot%nadded§3:§hotpot%n>add§lotusRoot%nadded§4:§lotusRoot%n>add§cabbage%nadded§5:§cabbage%n>add§goldNeedleFungus%nadded§6:§goldNe
edleFungus%n>add§winterMelon%nadded§7:§winterMelon%n>add§soupBase%nadded§8:§soupBase%n>add§tofu%nadded§9:§tofu%n>add§fishBalls%nadded§10:§fi
shBalls%n>add§potato%nadded§11:§potato%n>add-list§veggie%nadded§veggie%n>assign§6§5%nassigned§goldNeedleFungus§to§cabbage%n>assign§7§5%nassi
gned§winterMelon§to§cabbage%n>assign§1§3%nassigned§slicedBeef§to§hotpot%n>assign§2§10%nassigned§slicedLamb§to§fishBalls%n>assign§10§3%nassig
ned§fishBalls§to§hotpot%n>assign§5§4%nassigned§cabbage§to§lotusRoot%n>assign§4§3%nassigned§lotusRoot§to§hotpot%n>assign§9§10%nassigned§tofu§
to§fishBalls%n>assign§8§3%nassigned§soupBase§to§hotpot%n>assign§4§veggie%nassigned§lotusRoot§to§veggie%n>assign§9§veggie%nassigned§tofu§to§v
eggie%n>assign§11§veggie%nassigned§potato§to§veggie%n>list§veggie%n-§[§]§lotusRoot%n§§-§[§]§cabbage%n§§§§-§[§]§goldNeedleFungus%n§§§§-§[§]§w
interMelon%n-§[§]§tofu%n-§[§]§potato%n>todo%n-§[§]§hotpot%n§§-§[§]§slicedBeef%n§§-§[§]§fishBalls%n§§§§-§[§]§slicedLamb%n§§§§-§[§]§tofu%n§§-§
[§]§lotusRoot%n§§§§-§[§]§cabbage%n§§§§§§-§[§]§goldNeedleFungus%n§§§§§§-§[§]§winterMelon%n§§-§[§]§soupBase%n-§[§]§potato%n>delete§4%ndeleted§
lotusRoot§and§3§subtasks%n>delete§10%ndeleted§fishBalls§and§2§subtasks%n>delete§1%ndeleted§slicedBeef§and§0§subtasks%n>delete§11%ndeleted§po
tato§and§0§subtasks%n#%n#%n#§§(potato)§§§§§§§§§§§§§§§§§§§§§§§hotpot%n#§§§§§§§§§§§§§§§§§§§/§§§§§§§§§§§§/§§§§§§§§§§§\\§§§§§§§§§§§\\%n#§§§§§§§§
§§(fishBalls)§§§§§(slicedBeef)§§§§soupBase§§§§§(lotusRoot)%n#§§§§§§§§§§/§§§§§§§§\\§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§|%n#§§§(slicedLa
mb)§§§§(tofu)§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§(cabbage)%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§/§§§§§§§§§\\%n#§§§§§§§§§
§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§(goldNeedleFungus)§§§§(winterMelon)%n#%n#%n>list§veggie%n>todo%n-§[§]§hotpot%n§§-§[§]§soupBase%n>restore§11
%nrestored§potato§and§0§subtasks#§§§§§§§§§restore§top§level§without§subtask%n>restore§11%n!A!!R!^ERROR:§.*#§§§§§§§§§§§§§§§§§§§§§§§immediatel
y§rerestore§top§level§task%n>list§veggie%n-§[§]§potato%n>todo%n-§[§]§hotpot%n§§-§[§]§soupBase%n-§[§]§potato%n>restore§1%nrestored§slicedBeef
§and§0§subtasks#§§§§§restore§subtask§(existing§upper§task)§without§subtasks%n>restore§1%n!A!!R!^ERROR:§.*#§§§§§§§§§§§§§§§§§§§§§§§immediately
§rerestore§subtask%n>restore§9%nrestored§tofu§and§0§subtasks#§§§§§§§§§§§restore§subtask§(deleted§upper§task)§without§subtasks%n>show§3%n-§[§
]§hotpot%n§§-§[§]§soupBase%n§§-§[§]§slicedBeef%n>list§veggie%n-§[§]§potato%n-§[§]§tofu%n>restore§6%nrestored§goldNeedleFungus§and§0§subtasks
%n>restore§7%nrestored§winterMelon§and§0§subtasks%n>restore§5%nrestored§cabbage§and§0§subtasks#§§§§§§§§restore§subtask§(deleted§upper§task)§
with§already§restored§subtasks%n>list§veggie%n-§[§]§potato%n-§[§]§tofu%n-§[§]§goldNeedleFungus%n-§[§]§winterMelon%n-§[§]§cabbage%n>todo%n-§[
§]§hotpot%n§§-§[§]§soupBase%n§§-§[§]§slicedBeef%n-§[§]§potato%n-§[§]§tofu%n-§[§]§goldNeedleFungus%n-§[§]§winterMelon%n-§[§]§cabbage%n>assign
§9§7%nassigned§tofu§to§winterMelon%n>assign§7§8%nassigned§winterMelon§to§soupBase%n>show§8%n-§[§]§soupBase%n§§-§[§]§winterMelon%n§§§§-§[§]§t
ofu%n>show§3%n-§[§]§hotpot%n§§-§[§]§soupBase%n§§§§-§[§]§winterMelon%n§§§§§§-§[§]§tofu%n§§-§[§]§slicedBeef%n>toggle§8%ntoggled§soupBase§and§2
§subtasks%n>todo%n-§[§]§hotpot%n§§-§[§]§slicedBeef%n-§[§]§potato%n-§[§]§goldNeedleFungus%n-§[§]§cabbage%n>delete§8%ndeleted§soupBase§and§2§s
ubtasks%n>restore§7%nrestored§winterMelon§and§1§subtasks#§§§§§restore§subtask§(deleted§upper§task)§with§still§deleted§subtasks%n>todo%n-§[§]
§hotpot%n§§-§[§]§slicedBeef%n-§[§]§potato%n-§[§]§goldNeedleFungus%n-§[§]§cabbage%n>list§veggie%n-§[§]§potato%n-§[§]§goldNeedleFungus%n-§[§]§
cabbage%n-§[x]§winterMelon%n§§-§[x]§tofu%n>restore§9#§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§ensure§subtask§has§been§restored§aswell%n!A!!R!^ERROR:§.*
%n>delete§9%ndeleted§tofu§and§0§subtasks%n>toggle§7%ntoggled§winterMelon§and§0§subtasks%n>restore§9%nrestored§tofu§and§0§subtasks%n>todo%n-§
[§]§hotpot%n§§-§[§]§slicedBeef%n-§[§]§potato%n-§[§]§goldNeedleFungus%n-§[§]§cabbage%n-§[§]§winterMelon%n>list§veggie%n-§[§]§potato%n-§[§]§go
ldNeedleFungus%n-§[§]§cabbage%n-§[§]§winterMelon%n§§-§[x]§tofu%n>quit%Tname:§FUNCTIONAL§Basic:§todo%ncomment:§Tests§if§todo§command§basicall
y§behaves§as§expected%nargs:%n--%n>todo%n>add§1%nadded§1:§1%n>add§2%nadded§2:§2%n>add§3%nadded§3:§3%n>add§4%nadded§4:§4%n>add§5%nadded§5:§5%
n>assign§5§3%nassigned§5§to§3%n>assign§4§3%nassigned§4§to§3%n>assign§3§1%nassigned§3§to§1%n>todo%n-§[§]§1%n§§-§[§]§3%n§§§§-§[§]§5%n§§§§-§[§]
§4%n-§[§]§2%n>toggle§3%ntoggled§3§and§2§subtasks%n>todo%n-§[§]§1%n-§[§]§2%n>toggle§4%ntoggled§4§and§0§subtasks%n>todo%n-§[§]§1%n§§-§[x]§3%n§
§§§-§[§]§4%n-§[§]§2%n>toggle§5%ntoggled§5§and§0§subtasks%n>todo%n-§[§]§1%n§§-§[x]§3%n§§§§-§[§]§5%n§§§§-§[§]§4%n-§[§]§2%n>toggle§3%ntoggled§3
§and§2§subtasks%n>todo%n-§[§]§1%n§§-§[§]§3%n§§§§-§[§]§5%n§§§§-§[§]§4%n-§[§]§2%n>toggle§1%ntoggled§1§and§3§subtasks%n>todo%n-§[§]§2%n>toggle§
2%ntoggled§2§and§0§subtasks%n>todo%n>quit%Tname:§FUNCTIONAL§Mixed:§time%ncomment:§Tests§if§time§related§commands§behave§as§expected%nargs:%n
--%n>add§repair§2023-08-17%nadded§1:§repair%n>add§registrationDoc§2023-08-16%nadded§2:§registrationDoc%n>add§busTicket§2023-08-17%nadded§3:§
busTicket%n>add§loadCar§2023-08-15%nadded§4:§loadCar%n>add§cleanCar%nadded§5:§cleanCar%n>add§somethingToRead§2023-08-17%nadded§6:§somethingT
oRead%n>add§tüv§2024-08-31%nadded§7:§tüv%n>assign§2§1%nassigned§registrationDoc§to§repair%n>assign§5§4%nassigned§cleanCar§to§loadCar%n>assig
n§4§1%nassigned§loadCar§to§repair%n>upcoming§2023-08-15%n-§[§]§repair:§-->§2023-08-17%n§§-§[§]§registrationDoc:§-->§2023-08-16%n§§-§[§]§load
Car:§-->§2023-08-15%n§§§§-§[§]§cleanCar%n-§[§]§busTicket:§-->§2023-08-17%n-§[§]§somethingToRead:§-->§2023-08-17%n>before§2024-08-31%n-§[§]§r
epair:§-->§2023-08-17%n§§-§[§]§registrationDoc:§-->§2023-08-16%n§§-§[§]§loadCar:§-->§2023-08-15%n§§§§-§[§]§cleanCar%n-§[§]§busTicket:§-->§20
23-08-17%n-§[§]§somethingToRead:§-->§2023-08-17%n-§[§]§tüv:§-->§2024-08-31%n>between§2023-08-15§2024-08-31%n-§[§]§repair:§-->§2023-08-17%n§§
-§[§]§registrationDoc:§-->§2023-08-16%n§§-§[§]§loadCar:§-->§2023-08-15%n§§§§-§[§]§cleanCar%n-§[§]§busTicket:§-->§2023-08-17%n-§[§]§something
ToRead:§-->§2023-08-17%n-§[§]§tüv:§-->§2024-08-31%n>change-date§3§2023-08-14%nchanged§busTicket§to§2023-08-14%n>change-date§4§2023-08-14%nch
anged§loadCar§to§2023-08-14%n>upcoming§2023-08-15%n-§[§]§repair:§-->§2023-08-17%n§§-§[§]§registrationDoc:§-->§2023-08-16%n§§-§[§]§loadCar:§-
->§2023-08-14%n§§§§-§[§]§cleanCar%n-§[§]§somethingToRead:§-->§2023-08-17%n>before§2024-08-31%n-§[§]§repair:§-->§2023-08-17%n§§-§[§]§registra
tionDoc:§-->§2023-08-16%n§§-§[§]§loadCar:§-->§2023-08-14%n§§§§-§[§]§cleanCar%n-§[§]§busTicket:§-->§2023-08-14%n-§[§]§somethingToRead:§-->§20
23-08-17%n-§[§]§tüv:§-->§2024-08-31%n>between§2023-08-15§2024-08-31%n-§[§]§repair:§-->§2023-08-17%n§§-§[§]§registrationDoc:§-->§2023-08-16%n
§§-§[§]§loadCar:§-->§2023-08-14%n§§§§-§[§]§cleanCar%n-§[§]§somethingToRead:§-->§2023-08-17%n-§[§]§tüv:§-->§2024-08-31%n>toggle§5%ntoggled§cl
eanCar§and§0§subtasks%n>toggle§6%ntoggled§somethingToRead§and§0§subtasks%n>change-priority§5§HI%nchanged§cleanCar§to§HI%n>before§2023-08-31%
n-§[§]§repair:§-->§2023-08-17%n§§-§[§]§registrationDoc:§-->§2023-08-16%n§§-§[§]§loadCar:§-->§2023-08-14%n§§§§-§[x]§cleanCar§[HI]%n-§[§]§busT
icket:§-->§2023-08-14%n-§[x]§somethingToRead:§-->§2023-08-17%n>delete§1%ndeleted§repair§and§3§subtasks%n>upcoming§2023-08-15%n-§[x]§somethin
gToRead:§-->§2023-08-17%n>before§2024-08-31%n-§[§]§busTicket:§-->§2023-08-14%n-§[x]§somethingToRead:§-->§2023-08-17%n-§[§]§tüv:§-->§2024-08-
31%n>between§2023-08-15§2024-08-31%n-§[x]§somethingToRead:§-->§2023-08-17%n-§[§]§tüv:§-->§2024-08-31%n>restore§4%nrestored§loadCar§and§1§sub
tasks%n>upcoming§2023-08-14%n-§[§]§busTicket:§-->§2023-08-14%n-§[x]§somethingToRead:§-->§2023-08-17%n-§[§]§loadCar:§-->§2023-08-14%n§§-§[x]§
cleanCar§[HI]%n>before§2024-08-30%n-§[§]§busTicket:§-->§2023-08-14%n-§[x]§somethingToRead:§-->§2023-08-17%n-§[§]§loadCar:§-->§2023-08-14%n§§
-§[x]§cleanCar§[HI]%n>between§2023-08-14§2024-08-31%n-§[§]§busTicket:§-->§2023-08-14%n-§[x]§somethingToRead:§-->§2023-08-17%n-§[§]§tüv:§-->§
2024-08-31%n-§[§]§loadCar:§-->§2023-08-14%n§§-§[x]§cleanCar§[HI]%n>change-date§6§9999-12-31%nchanged§somethingToRead§to§9999-12-31%n>change-
date§7§0000-01-01%nchanged§tüv§to§0000-01-01%n>restore§1%nrestored§repair§and§1§subtasks%n>upcoming§9999-12-31%n-§[x]§somethingToRead:§-->§9
999-12-31%n>upcoming§0000-01-01%n-§[§]§tüv:§-->§0000-01-01%n>before§9999-12-31%n-§[§]§busTicket:§-->§2023-08-14%n-§[x]§somethingToRead:§-->§
9999-12-31%n-§[§]§tüv:§-->§0000-01-01%n-§[§]§loadCar:§-->§2023-08-14%n§§-§[x]§cleanCar§[HI]%n-§[§]§repair:§-->§2023-08-17%n§§-§[§]§registrat
ionDoc:§-->§2023-08-16%n>toggle§1%ntoggled§repair§and§1§subtasks%n>toggle§2%ntoggled§registrationDoc§and§0§subtasks%n>toggle§3%ntoggled§busT
icket§and§0§subtasks%n>toggle§4%ntoggled§loadCar§and§1§subtasks%n>toggle§6%ntoggled§somethingToRead§and§0§subtasks%n>toggle§7%ntoggled§tüv§a
nd§0§subtasks%n>between§0000-01-01§9999-12-31%n-§[x]§busTicket:§-->§2023-08-14%n-§[§]§somethingToRead:§-->§9999-12-31%n-§[x]§tüv:§-->§0000-0
1-01%n-§[x]§loadCar:§-->§2023-08-14%n§§-§[x]§cleanCar§[HI]%n-§[x]§repair:§-->§2023-08-17%n§§-§[§]§registrationDoc:§-->§2023-08-16%n>quit%Tna
me:§FUNCTIONAL§Basic:§tag%ncomment:§Tests§if§tag§command§basically§behaves§as§expected%nargs:%n--%n#§§§§§§§setup§requirements%n>add§function
alBasicTagTask%nadded§1:§functionalBasicTagTask%n>add§functionalBasicTagTaskTwo%nadded§2:§functionalBasicTagTaskTwo%n>add-list§functionalBas
icTagList%nadded§functionalBasicTagList%n>add-list§functionalBasicTagListTwo%nadded§functionalBasicTagListTwo%n#§§§§§§§test§tag§command§for§
tasks%n>tag§1§niceTag%ntagged§functionalBasicTagTask§with§niceTag%n>tag§1§niceTag%n!A!!R!^ERROR:§.*%n>tag§1§evenNicerTag%ntagged§functionalB
asicTagTask§with§evenNicerTag%n>tag§1§evenNicerTag%n!A!!R!^ERROR:§.*%n>tag§1§niceTag%n!A!!R!^ERROR:§.*%n>tag§2§niceTag%ntagged§functionalBas
icTagTaskTwo§with§niceTag#multiple§tasks§same§tag%n>tag§2§niceTag%n!A!!R!^ERROR:§.*%n>tag§2§evenNicerTag%ntagged§functionalBasicTagTaskTwo§w
ith§evenNicerTag%n>tag§2§evenNicerTag%n!A!!R!^ERROR:§.*%n>tag§2§niceTag%n!A!!R!^ERROR:§.*%n#§§§§§§§test§tag§command§for§lists%n>tag§function
alBasicTagList§niceTagForAList%ntagged§functionalBasicTagList§with§niceTagForAList%n>tag§functionalBasicTagList§niceTagForAList%n!A!!R!^ERRO
R:§.*%n>tag§functionalBasicTagList§evenNicerTagForAList%ntagged§functionalBasicTagList§with§evenNicerTagForAList%n>tag§functionalBasicTagLis
t§evenNicerTagForAList%n!A!!R!^ERROR:§.*%n>tag§functionalBasicTagList§niceTagForAList%n!A!!R!^ERROR:§.*%n>tag§functionalBasicTagListTwo§nice
TagForAList%ntagged§functionalBasicTagListTwo§with§niceTagForAList%n>tag§functionalBasicTagListTwo§niceTagForAList%n!A!!R!^ERROR:§.*%n>tag§f
unctionalBasicTagListTwo§evenNicerTagForAList%ntagged§functionalBasicTagListTwo§with§evenNicerTagForAList%n>tag§functionalBasicTagListTwo§ev
enNicerTagForAList%n!A!!R!^ERROR:§.*%n>tag§functionalBasicTagListTwo§niceTagForAList%n!A!!R!^ERROR:§.*%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLI
NG:§change-date%ncomment:§Tests§if§the§parameters§are§parsed§correctly,§no§working§model§expected%nargs:%n--%n>add§task%n!R!^(?!ERROR:§).*$%
n>change-date%n!A!!R!^ERROR:§.*%n>change-date§1%n!A!!R!^ERROR:§.*%n>change-date§1§2023-08-01§2023-08-01%n!A!!R!^ERROR:§.*%n>change-date§1§20
23-07-32%n!A!!R!^ERROR:§.*%n>change-date§1§2023-07-00%n!A!!R!^ERROR:§.*%n>change-date§1§2023-13-01%n!A!!R!^ERROR:§.*%n>change-date§1§2023-00
-01%n!A!!R!^ERROR:§.*%n>change-date§1§2023-02-29%n!A!!R!^ERROR:§.*%n>change-date§1§23-08-01%n!A!!R!^ERROR:§.*%n>change-date§1§01.08.2023%n!A
!!R!^ERROR:§.*%n>change-date§1§2023.08.01%n!A!!R!^ERROR:§.*%n>change-date§1§2023-02-01%n!R!^(?!ERROR:§).*$%n>change-date§1§2024-02-29%n!R!^(
?!ERROR:§).*$%n>change-date§1§0000-01-01%n!R!^(?!ERROR:§).*$%n>change-date§1§9999-12-31%n!R!^(?!ERROR:§).*$%n>quit%Tname:§FUNCTIONAL§ERROR§H
ANDLING:§upcoming%ncomment:§Tests§if§the§parameters§are§parsed§correctly,§no§working§model§expected%nargs:%n--%n>upcoming§1%n!A!!R!^ERROR:§.
*%n>upcoming§whatever%n!A!!R!^ERROR:§.*%n>upcoming%n!A!!R!^ERROR:§.*%n>upcoming§2023-06-31%n!A!!R!^ERROR:§.*%n>upcoming§2023-05-01%n>upcomin
g§2020-02-29%n>upcoming§0000-01-01%n>upcoming§9999-12-31%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLING:§tag%ncomment:§Tests§if§the§parameters§are§
parsed§correctly,§no§working§model§expected%nargs:%n--%n>add§task%n!R!^(?!ERROR:§).*$%n>add-list§list%n!R!^(?!ERROR:§).*$%n>tag%n!A!!R!^ERRO
R:§.*%n>tag§1%n!A!!R!^ERROR:§.*%n>tag§1§tag§whatever%n!A!!R!^ERROR:§.*%n>tag§1§tag_1%n!A!!R!^ERROR:§.*%n>tag§1§aTag%n!R!^(?!ERROR:§).*$%n>ta
g§list%n!A!!R!^ERROR:§.*%n>tag§list§tag§whatever%n!A!!R!^ERROR:§.*%n>tag§list§my_first_tag%n!A!!R!^ERROR:§.*%n>tag§list§anotherTag%n!R!^(?!E
RROR:§).*$%n>quit%Tname:§FUNCTIONAL§Basic:§tags%ncomment:§Tests§if§tag§related§commands§behave§as§expected%nargs:%n--%n>add§idioms%nadded§1:
§idioms%n>add§āiyānǐbié#§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§you§didn't§have§to§do%nadded§2:§āiyānǐbié%n>add§dàhǎilāozhēn#§§§§§§§§§§§§
§§§§§§§§§§§§§§§§§§§§§§§§§§§§finding§a§needle§in§the§haystackc%nadded§3:§dàhǎilāozhēn%n>add§jíshíxínglè#§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§
§§§§carpe§diem%nadded§4:§jíshíxínglè%n>add§xiǎoxīnméimìng#§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§careful,§don't§die%nadded§5:§xiǎoxīnméimìng%
n>add§shēntǐjiànkāng#§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§wish§you§good§health§(weit§verbreitet)%nadded§6:§shēntǐjiànkāng%n>add§mǎmǎhǔhǔ§20
23-05-10#§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§so§so§(geht§so)%nadded§7:§mǎmǎhǔhǔ%n>add§gěinǐsānfēnyánsè,nǐjiùkāiqǐlerǎnfáng§2023-09-01#§§§§§you'
re§taking§it§way§too§far%nadded§8:§gěinǐsānfēnyánsè,nǐjiùkāiqǐlerǎnfáng%n>assign§8§1%nassigned§gěinǐsānfēnyánsè,nǐjiùkāiqǐlerǎnfáng§to§idiom
s%n>assign§6§1%nassigned§shēntǐjiànkāng§to§idioms%n>assign§3§5%nassigned§dàhǎilāozhēn§to§xiǎoxīnméimìng%n>assign§5§1%nassigned§xiǎoxīnméimìn
g§to§idioms%n>todo%n-§[§]§idioms%n§§-§[§]§gěinǐsānfēnyánsè,nǐjiùkāiqǐlerǎnfáng:§-->§2023-09-01%n§§-§[§]§shēntǐjiànkāng%n§§-§[§]§xiǎoxīnméimì
ng%n§§§§-§[§]§dàhǎilāozhēn%n-§[§]§āiyānǐbié%n-§[§]§jíshíxínglè%n-§[§]§mǎmǎhǔhǔ:§-->§2023-05-10%n>tag§7§daily%ntagged§mǎmǎhǔhǔ§with§daily%n>t
ag§4§daily%ntagged§jíshíxínglè§with§daily%n>tag§5§daily%ntagged§xiǎoxīnméimìng§with§daily%n>tag§8§useful%ntagged§gěinǐsānfēnyánsè,nǐjiùkāiqǐ
lerǎnfáng§with§useful%n>tag§5§useful%ntagged§xiǎoxīnméimìng§with§useful%n>tag§7§lecture2%ntagged§mǎmǎhǔhǔ§with§lecture2%n>tag§1§online%ntagg
ed§idioms§with§online%n>todo%n-§[§]§idioms:§(online)%n§§-§[§]§gěinǐsānfēnyánsè,nǐjiùkāiqǐlerǎnfáng:§(useful)§-->§2023-09-01%n§§-§[§]§shēntǐj
iànkāng%n§§-§[§]§xiǎoxīnméimìng:§(daily,§useful)%n§§§§-§[§]§dàhǎilāozhēn%n-§[§]§āiyānǐbié%n-§[§]§jíshíxínglè:§(daily)%n-§[§]§mǎmǎhǔhǔ:§(dail
y,§lecture2)§-->§2023-05-10%n>tagged-with§online%n-§[§]§idioms:§(online)%n§§-§[§]§gěinǐsānfēnyánsè,nǐjiùkāiqǐlerǎnfáng:§(useful)§-->§2023-09
-01%n§§-§[§]§shēntǐjiànkāng%n§§-§[§]§xiǎoxīnméimìng:§(daily,§useful)%n§§§§-§[§]§dàhǎilāozhēn%n>tagged-with§daily%n-§[§]§jíshíxínglè:§(daily)
%n-§[§]§xiǎoxīnméimìng:§(daily,§useful)%n§§-§[§]§dàhǎilāozhēn%n-§[§]§mǎmǎhǔhǔ:§(daily,§lecture2)§-->§2023-05-10%n>tagged-with§useful%n-§[§]§
gěinǐsānfēnyánsè,nǐjiùkāiqǐlerǎnfáng:§(useful)§-->§2023-09-01%n-§[§]§xiǎoxīnméimìng:§(daily,§useful)%n§§-§[§]§dàhǎilāozhēn%n>delete§5%ndelet
ed§xiǎoxīnméimìng§and§1§subtasks%n>tagged-with§online%n-§[§]§idioms:§(online)%n§§-§[§]§gěinǐsānfēnyánsè,nǐjiùkāiqǐlerǎnfáng:§(useful)§-->§20
23-09-01%n§§-§[§]§shēntǐjiànkāng%n>tagged-with§daily%n-§[§]§jíshíxínglè:§(daily)%n-§[§]§mǎmǎhǔhǔ:§(daily,§lecture2)§-->§2023-05-10%n>tagged-
with§useful%n-§[§]§gěinǐsānfēnyánsè,nǐjiùkāiqǐlerǎnfáng:§(useful)§-->§2023-09-01%n>restore§3%nrestored§dàhǎilāozhēn§and§0§subtasks%n>restore
§5%nrestored§xiǎoxīnméimìng§and§0§subtasks%n>tagged-with§online%n-§[§]§idioms:§(online)%n§§-§[§]§gěinǐsānfēnyánsè,nǐjiùkāiqǐlerǎnfáng:§(usef
ul)§-->§2023-09-01%n§§-§[§]§shēntǐjiànkāng%n§§-§[§]§xiǎoxīnméimìng:§(daily,§useful)%n>tagged-with§daily%n-§[§]§jíshíxínglè:§(daily)%n-§[§]§x
iǎoxīnméimìng:§(daily,§useful)%n-§[§]§mǎmǎhǔhǔ:§(daily,§lecture2)§-->§2023-05-10%n>tagged-with§useful%n-§[§]§gěinǐsānfēnyánsè,nǐjiùkāiqǐlerǎ
nfáng:§(useful)§-->§2023-09-01%n-§[§]§xiǎoxīnméimìng:§(daily,§useful)%n>add-list§useless%nadded§useless%n>tag§useless§soso%ntagged§useless§w
ith§soso%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLING:§tagged-with%ncomment:§Tests§if§the§parameters§are§parsed§correctly,§no§working§model§expec
ted%nargs:%n--%n>tagged-with%n!A!!R!^ERROR:§.*%n>tagged-with§tag§whatever%n!A!!R!^ERROR:§.*%n>tagged-with§tag§1%n!A!!R!^ERROR:§.*%n>tagged-w
ith§tag_1%n!A!!R!^ERROR:§.*%n>tagged-with§2023-08-01%n!A!!R!^ERROR:§.*%n>tagged-with§aTag1%n!R!^(?!ERROR:§).*$%n>quit%Tname:§FUNCTIONAL§Basi
c:§restore§for§tasks%ncomment:§Tests§if§restore§command§basically§behaves§as§expected§for§tasks,§lists§ignored%nargs:%n--%n#setup%n>add§swee
ts%nadded§1:§sweets%n>add§nimm2%nadded§2:§nimm2%n>add§cookies%nadded§3:§cookies%n>add§toffifee%nadded§4:§toffifee%n>add§chocolate%nadded§5:§
chocolate%n>add§toblerone%nadded§6:§toblerone%n>add§salad%nadded§7:§salad%n>add§bonbon%nadded§8:§bonbon%n>add§nonCookies%nadded§9:§nonCookie
s%n>assign§6§5%nassigned§toblerone§to§chocolate%n>assign§5§9%nassigned§chocolate§to§nonCookies%n>assign§2§8%nassigned§nimm2§to§bonbon%n>assi
gn§4§8%nassigned§toffifee§to§bonbon%n>assign§8§9%nassigned§bonbon§to§nonCookies%n>assign§9§1%nassigned§nonCookies§to§sweets%n>assign§3§1%nas
signed§cookies§to§sweets%n#§§§§§§§salad§§§§§§§§§§§§§§§§§§§§§§§§§§sweets%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§/§§§§§§§§§§\\%n#§§§§§§§§§§§§§§§
§§§§§§§§§§§§§nonCookies§§§§§§§cookies%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§§/§§§§§§§§\\%n#§§§§§§§§§§§§§§§§§§§§§§§bonbon§§§§§§chocolate%n#§§§§§§§§§§§
§§§§§§§§§§§/§§§§§\\§§§§§§§§§§|%n#§§§§§§§§§§§§§§§§§nimm2§§§toffifee§§§§toblerone%n>delete§7%ndeleted§salad§and§0§subtasks%n>delete§9%ndeleted
§nonCookies§and§5§subtasks%n>delete§3%ndeleted§cookies§and§0§subtasks%n#§§§§§§§(salad)§§§§§§§§§§§§§§§§§§§§§§§§sweets%n#§§§§§§§§§§§§§§§§§§§§§
§§§§§§§§§§§§§§/§§§§§§§§§§\\%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§(nonCookies)§§§§§(cookies)%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§§/§§§§§§§§\\%n#§§§§§§§§§§§§
§§§§§§§§§§(bonbon)§§§§§(chocolate)%n#§§§§§§§§§§§§§§§§§§§§§§/§§§§§\\§§§§§§§§§§§§§\\%n#§§§§§§§§§§§§§§§§(nimm2)§§§(toffifee)§§§§(toblerone)%n#t
est§restore%n>restore§7%nrestored§salad§and§0§subtasks#§§§§§§§restore§top§level§without§subtask%n>restore§7%n!A!!R!^ERROR:§.*#§§§§§§§§§§§§§§
§§§§§§immediately§rerestore§top§level§task%n>restore§3%nrestored§cookies§and§0§subtasks#§§§§§restore§subtask§(existing§upper§task)§without§s
ubtasks%n>restore§3%n!A!!R!^ERROR:§.*#§§§§§§§§§§§§§§§§§§§§immediately§rerestore§subtask%n#%n#%n#§§§§§§§salad§§§§§§§§§§§§§§§§§§§§§§§§§§sweets
%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§/§§§§§§§§§§\\%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§(nonCookies)§§§§§§cookies%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§§/§§
§§§§§§\\%n#§§§§§§§§§§§§§§§§§§§§§§(bonbon)§§§§§(chocolate)%n#§§§§§§§§§§§§§§§§§§§§§§/§§§§§\\§§§§§§§§§§§§§\\%n#§§§§§§§§§§§§§§§§(nimm2)§§§(toffi
fee)§§§§(toblerone)%n#%n#%n>restore§6%nrestored§toblerone§and§0§subtasks#§§§restore§subtask§(deleted§upper§task)§without§subtasks%n#%n#%n#§§
§§§§§salad§§§§§§§§§§§§§§§§§§§§§§§§§§sweets§§§§§§§§§§§§§§§§toblerone%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§/§§§§§§§§§§\\%n#§§§§§§§§§§§§§§§§§§§
§§§§§§§§(nonCookies)§§§§§§cookies%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§§/§§§§§§§§\\%n#§§§§§§§§§§§§§§§§§§§§§§(bonbon)§§§§§(chocolate)%n#§§§§§§§§§§§§§
§§§§§§§§§/§§§§§\\%n#§§§§§§§§§§§§§§§§(nimm2)§§§(toffifee)%n#%n#%n>restore§5%nrestored§chocolate§and§0§subtasks#§§§restore§subtask§(deleted§up
per§task)§with§already§restored§subtasks%n#%n#%n#§§§§§§§salad§§§§§§§§§§§§§§§§§§§§§§§§§§sweets§§§§§§§§§§§toblerone§§§§chocolate%n#§§§§§§§§§§§
§§§§§§§§§§§§§§§§§§§§§§§§/§§§§§§§§§§\\%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§(nonCookies)§§§§§§cookies%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§§/%n#§§§§§§§§§§§§§
§§§§§§§§§(bonbon)%n#§§§§§§§§§§§§§§§§§§§§§§/§§§§§\\%n#§§§§§§§§§§§§§§§§(nimm2)§§§(toffifee)%n#%n#%n>assign§6§5%nassigned§toblerone§to§chocolat
e#§§§§§reassign§now§top§level§task§to§former§upper§task,§ensuring§previous§connection§has§been§removed%n>assign§6§5%n!A!!R!^ERROR:§.*#§§§§§§
§§§§§§§§§§§§§§recall§to§ensure§proper§behavior§§§§§§§§§§§§§§§§§§%n>restore§8%nrestored§bonbon§and§2§subtasks#§§§§§§restore§subtask§(deleted§
upper§task)§with§still§deleted§subtasks%n#%n#%n#§§§§§§§salad§§§§§§§§§§§§§§§§§§§§§§§§§§sweets§§§§§§§§§§§§chocolate§§§§§§§§§§§§§bonbon§§§%n#§§
§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§§/§§§§§§§§§§\\§§§§§§§§§§§§§|§§§§§§§§§§§§§§§§/§§§§§§§\\%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§(nonCookies)§§§§§§cookie
s§§§§toblerone§§§§§§§§nimm2§§§§§§toffifee%n#§%n#%n>restore§2#§§§§§§§§§§§§§§§§§§§§§§§§§§ensure§subtask§has§been§restored§aswell%n!A!!R!^ERROR
:§.*%n>restore§4#§§§§§§§§§§§§§§§§§§§§§§§§§§ensure§subtask§has§been§restored§aswell%n!A!!R!^ERROR:§.*%n>restore§9%nrestored§nonCookies§and§0§
subtasks#§§restore§subtask§(existing§upper§task)§with§already§restored§subtasks%n>assign§8§9%nassigned§bonbon§to§nonCookies%n>delete§9%ndele
ted§nonCookies§and§3§subtasks%n>restore§9%nrestored§nonCookies§and§3§subtasks#§§restore§subtask§(existing§upper§task)§with§still§deleted§sub
tasks%n>restore§8%n!A!!R!^ERROR:§.*#§§§§§§§§§§§§§§§§§§§§ensure§subtask§has§been§restored§aswell%n>restore§2%n!A!!R!^ERROR:§.*#§§§§§§§§§§§§§§
§§§§§§ensure§subtask§has§been§restored§aswell%n>restore§4%n!A!!R!^ERROR:§.*#§§§§§§§§§§§§§§§§§§§§ensure§subtask§has§been§restored§aswell%n#%n
#%n#§§§§§salad§§§§§§§sweets§§§§§§§§chocolate%n#§§§§§§§§§§§§§§§§/§§§§§\\§§§§§§§§§§§§|%n#§§§§§§§§nonCookies§§§cookies§§§§toblerone%n#§§§§§§§§§
§§§|%n#§§§§§§§§§bonbon%n#§§§§§§§§§/§§§§\\%n#§§§§§nimm2§§toffifee%n#%n#%n>delete§1%ndeleted§sweets§and§5§subtasks%n>restore§1%nrestored§sweet
s§and§5§subtasks#§§§§§§restore§top§level§with§subtasks%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLING:§list%ncomment:§Tests§if§the§parameters§are§p
arsed§correctly,§no§working§model§expected%nargs:%n--%n>add-list§list%nadded§list%n>list§1%n!A!!R!^ERROR:§.*%n>list§tsil%n!A!!R!^ERROR:§.*%n
>list§list%n!R!^(?!ERROR:§).*$%n>list§list§list%n!A!!R!^ERROR:§.*%n>quit%Tname:§Example§Interaction%ncomment:§Tests§if§the§example§interacti
on§is§executed§correctly.%nargs:%n--%n>add§Final1§HI§2023-07-31%nadded§1:§Final1%n>add§complete_commands§MD§2023-07-26%nadded§2:§complete_co
mmands%n>add§command_add%nadded§3:§command_add%n>toggle§3%ntoggled§command_add§and§0§subtasks%n>add§command_assign§MD%nadded§4:§command_assi
gn%n>add§command_show§2023-07-25%nadded§5:§command_show%n>assign§3§2%nassigned§command_add§to§complete_commands%n>toggle§4%ntoggled§command_
assign§and§0§subtasks%n>assign§4§2%nassigned§command_assign§to§complete_commands%n>add-list§timeCommands%nadded§timeCommands%n>assign§3§time
Commands%nassigned§command_add§to§timeCommands%n>add§command_change-date%nadded§6:§command_change-date%n>assign§6§2%nassigned§command_change
-date§to§complete_commands%n>assign§6§timeCommands%nassigned§command_change-date§to§timeCommands%n>tag§2§incomplete%ntagged§complete_command
s§with§incomplete%n>add§check_for_leap_year§2024-02-29%nadded§7:§check_for_leap_year%n>assign§7§3%nassigned§check_for_leap_year§to§command_a
dd%n>assign§2§1%nassigned§complete_commands§to§Final1%n>show§1%n-§[§]§Final1§[HI]:§-->§2023-07-31%n§§-§[§]§complete_commands§[MD]:§(incomple
te)§-->§2023-07-26%n§§§§-§[x]§command_assign§[MD]%n§§§§-§[x]§command_add%n§§§§§§-§[§]§check_for_leap_year:§-->§2024-02-29%n§§§§-§[§]§command
_change-date%n>toggle§5%ntoggled§command_show§and§0§subtasks%n>change-date§6§2023-07-27%nchanged§command_change-date§to§2023-07-27%n>toggle§
6%ntoggled§command_change-date§and§0§subtasks%n>upcoming§2023-07-26%n-§[§]§Final1§[HI]:§-->§2023-07-31%n§§-§[§]§complete_commands§[MD]:§(inc
omplete)§-->§2023-07-26%n§§§§-§[x]§command_assign§[MD]%n§§§§-§[x]§command_add%n§§§§§§-§[§]§check_for_leap_year:§-->§2024-02-29%n§§§§-§[x]§co
mmand_change-date:§-->§2023-07-27%n>add§variations_of_optional_parameters§LO%nadded§8:§variations_of_optional_parameters%n>assign§8§3%nassig
ned§variations_of_optional_parameters§to§command_add%n>list§timeCommands%n-§[x]§command_add%n§§-§[§]§variations_of_optional_parameters§[LO]%
n§§-§[§]§check_for_leap_year:§-->§2024-02-29%n-§[x]§command_change-date:§-->§2023-07-27%n>delete§3%ndeleted§command_add§and§2§subtasks%n>lis
t§timeCommands%n-§[x]§command_change-date:§-->§2023-07-27%n>show§1%n-§[§]§Final1§[HI]:§-->§2023-07-31%n§§-§[§]§complete_commands§[MD]:§(inco
mplete)§-->§2023-07-26%n§§§§-§[x]§command_assign§[MD]%n§§§§-§[x]§command_change-date:§-->§2023-07-27%n>restore§3%nrestored§command_add§and§2
§subtasks%n>tagged-with§incomplete%n-§[§]§complete_commands§[MD]:§(incomplete)§-->§2023-07-26%n§§-§[x]§command_assign§[MD]%n§§-§[x]§command_
change-date:§-->§2023-07-27%n§§-§[x]§command_add%n§§§§-§[§]§variations_of_optional_parameters§[LO]%n§§§§-§[§]§check_for_leap_year:§-->§2024-
02-29%n>toggle§7%ntoggled§check_for_leap_year§and§0§subtasks%n>todo%n-§[§]§Final1§[HI]:§-->§2023-07-31%n§§-§[§]§complete_commands§[MD]:§(inc
omplete)§-->§2023-07-26%n§§§§-§[x]§command_add%n§§§§§§-§[§]§variations_of_optional_parameters§[LO]%n>add§check_for_leap_year%nadded§9:§check
_for_leap_year%n>assign§9§6%nassigned§check_for_leap_year§to§command_change-date%n>duplicates%nFound§2§duplicates:§7,§9%n>before§2023-07-30%
n-§[§]§complete_commands§[MD]:§(incomplete)§-->§2023-07-26%n§§-§[x]§command_assign§[MD]%n§§-§[x]§command_change-date:§-->§2023-07-27%n§§§§-§
[§]§check_for_leap_year%n§§-§[x]§command_add%n§§§§-§[§]§variations_of_optional_parameters§[LO]%n§§§§-§[x]§check_for_leap_year:§-->§2024-02-2
9%n-§[x]§command_show:§-->§2023-07-25%n>change-priority§8§HI%nchanged§variations_of_optional_parameters§to§HI%n>tag§timeCommands§confusing%n
tagged§timeCommands§with§confusing%n>find§s%n-§[§]§complete_commands§[MD]:§(incomplete)§-->§2023-07-26%n§§-§[x]§command_assign§[MD]%n§§-§[x]
§command_change-date:§-->§2023-07-27%n§§§§-§[§]§check_for_leap_year%n§§-§[x]§command_add%n§§§§-§[§]§variations_of_optional_parameters§[HI]%n
§§§§-§[x]§check_for_leap_year:§-->§2024-02-29%n-§[x]§command_show:§-->§2023-07-25%n>toggle§1%ntoggled§Final1§and§7§subtasks%n>between§2023-0
1-01§2023-12-31%n-§[x]§Final1§[HI]:§-->§2023-07-31%n§§-§[x]§complete_commands§[MD]:§(incomplete)§-->§2023-07-26%n§§§§-§[x]§command_assign§[M
D]%n§§§§-§[x]§command_change-date:§-->§2023-07-27%n§§§§§§-§[x]§check_for_leap_year%n§§§§-§[x]§command_add%n§§§§§§-§[x]§variations_of_optiona
l_parameters§[HI]%n§§§§§§-§[x]§check_for_leap_year:§-->§2024-02-29%n-§[x]§command_show:§-->§2023-07-25%n>quit%Tname:§FUNCTIONAL§Basic:§dupli
cate%ncomment:§Tests§if§duplicate§command§behaves§as§expected%nargs:%n--%n>duplicates%nFound§0§duplicates:§%n>add§water%nadded§1:§water%n>du
plicates%nFound§0§duplicates:§%n>add§milk%nadded§2:§milk%n>duplicates%nFound§0§duplicates:§%n>add§water#§§§§§§§§§§§§§§§§§§§§§§§§§§§§with§1,§
no§date%nadded§3:§water%n>duplicates%nFound§2§duplicates:§1,§3%n>add§milk§2023-10-16#§§§§§§§§§§§§§§§§§§with§2,§1§date%nadded§4:§milk%n>dupli
cates%nFound§4§duplicates:§1,§2,§3,§4%n>add§tea§2025-02-01#§§§§§§§§§§§§§§§§§§§prepare§for§identical§date%nadded§5:§tea%n>duplicates%nFound§4
§duplicates:§1,§2,§3,§4%n>add§tea§2025-02-01#§§§§§§§§§§§§§§§§§§§identical§date%nadded§6:§tea%n>duplicates%nFound§6§duplicates:§1,§2,§3,§4,§5
,§6%n>assign§6§1#§§§§§§§§§§§§§§§§§§§§§§§§§§§ensuring§subtasks§count%nassigned§tea§to§water%n>duplicates%nFound§6§duplicates:§1,§2,§3,§4,§5,§
6%n>add§space#§§§§§§§§§§§§§§§§§§§§§§§§§§§§skip§numbers%nadded§7:§space%n>add§space2#§§§§§§§§§§§§§§§§§§§§§§§§§§§skip§numbers,§ensure§similar§
names§do§not§count%nadded§8:§space2%n>duplicates%nFound§6§duplicates:§1,§2,§3,§4,§5,§6%n>add§milk§2023-11-02#§§§§§§§§§§§§§§§§§§triplet%nadde
d§9:§milk%n>duplicates%nFound§7§duplicates:§1,§2,§3,§4,§5,§6,§9%n>delete§2#§§§§§§§§§§§§§§§§§§§§§§§§§§§§§delete§connection§part§of§triplet%nd
eleted§milk§and§0§subtasks%n>duplicates%nFound§4§duplicates:§1,§3,§5,§6%n>delete§5%ndeleted§tea§and§0§subtasks%n>duplicates%nFound§2§duplica
tes:§1,§3%n>delete§1%ndeleted§water§and§1§subtasks%n>duplicates%nFound§0§duplicates:§%n>restore§2#§§§§§§§§§§§§§§§§§§§§§§§§§§§§check§various§
manipulation§commands§to§ensure§nothing§influences§duplicates%nrestored§milk§and§0§subtasks%n>duplicates%nFound§3§duplicates:§2,§4,§9%n>chan
ge-date§2§2023-11-02%nchanged§milk§to§2023-11-02%n>duplicates%nFound§2§duplicates:§2,§9%n>toggle§2%ntoggled§milk§and§0§subtasks%n>duplicates
%nFound§2§duplicates:§2,§9%n>tag§2§aTag%ntagged§milk§with§aTag%n>duplicates%nFound§2§duplicates:§2,§9%n>change-priority§2§HI%nchanged§milk§t
o§HI%n>duplicates%nFound§2§duplicates:§2,§9%n>add-list§aList%nadded§aList%n>assign§2§aList%nassigned§milk§to§aList%n>duplicates%nFound§2§dup
licates:§2,§9%n>add§noSameDate§2023-10-10%nadded§10:§noSameDate%n>add§noSameDate§2023-10-11%nadded§11:§noSameDate%n>duplicates%nFound§2§dupl
icates:§2,§9%n>quit%Tname:§FUNCTIONAL§Mixed:§minor§important§things%ncomment:§Long§protocol§with§realistic§behavior%nargs:%n--%n>add§small_t
asks%nadded§1:§small_tasks%n>add§sheet1%nadded§2:§sheet1%n>assign§2§1%nassigned§sheet1§to§small_tasks%n>add§sheet2%nadded§3:§sheet2%n>assign
§3§1%nassigned§sheet2§to§small_tasks%n>change-date§2§2023-11-05%nchanged§sheet1§to§2023-11-05%n>change-date§3§2023-11-19%nchanged§sheet2§to§
2023-11-19%n>add§sheet3§2023-12-03%nadded§4:§sheet3%n>assign§4§1%nassigned§sheet3§to§small_tasks%n>add§sheet4§2023-12-17%nadded§5:§sheet4%n>
assign§5§1%nassigned§sheet4§to§small_tasks%n>add§sheet5§2024-01-21%nadded§6:§sheet5%n>assign§6§1%nassigned§sheet5§to§small_tasks%n>todo%n-§[
§]§small_tasks%n§§-§[§]§sheet1:§-->§2023-11-05%n§§-§[§]§sheet2:§-->§2023-11-19%n§§-§[§]§sheet3:§-->§2023-12-03%n§§-§[§]§sheet4:§-->§2023-12-
17%n§§-§[§]§sheet5:§-->§2024-01-21%n>add§learn_java§HI§2023-09-30%nadded§7:§learn_java%n>add§exceptions§MD%nadded§8:§exceptions%n>assign§8§7
%nassigned§exceptions§to§learn_java%n>add§streams§LO%nadded§9:§streams%n>assign§9§7%nassigned§streams§to§learn_java%n>toggle§8%ntoggled§exce
ptions§and§0§subtasks%n>add§learn_git§HI§2023-09-30%nadded§10:§learn_git%n>add§command_pattern%nadded§11:§command_pattern%n>assign§11§4%nass
igned§command_pattern§to§sheet3%n>add§error_handling%nadded§12:§error_handling%n>assign§12§6%nassigned§error_handling§to§sheet5%n>toggle§12%
ntoggled§error_handling§and§0§subtasks%n>show§1%n-§[§]§small_tasks%n§§-§[§]§sheet1:§-->§2023-11-05%n§§-§[§]§sheet2:§-->§2023-11-19%n§§-§[§]§
sheet3:§-->§2023-12-03%n§§§§-§[§]§command_pattern%n§§-§[§]§sheet4:§-->§2023-12-17%n§§-§[§]§sheet5:§-->§2024-01-21%n§§§§-§[x]§error_handling%
n>add§don_use_as_lazy_shortcut%nadded§13:§don_use_as_lazy_shortcut%n>assign§13§8%nassigned§don_use_as_lazy_shortcut§to§exceptions%n>add§stre
ams§MD§2023-09-30%nadded§14:§streams%n>assign§14§7%nassigned§streams§to§learn_java%n>toggle§4%ntoggled§sheet3§and§1§subtasks%n>todo%n-§[§]§l
earn_java§[HI]:§-->§2023-09-30%n§§-§[x]§exceptions§[MD]%n§§§§-§[§]§don_use_as_lazy_shortcut%n§§-§[§]§streams§[MD]:§-->§2023-09-30%n§§-§[§]§s
treams§[LO]%n-§[§]§learn_git§[HI]:§-->§2023-09-30%n-§[§]§small_tasks%n§§-§[§]§sheet1:§-->§2023-11-05%n§§-§[§]§sheet2:§-->§2023-11-19%n§§-§[§
]§sheet4:§-->§2023-12-17%n§§-§[§]§sheet5:§-->§2024-01-21%n>add§modeling_task%nadded§15:§modeling_task%n>assign§15§2%nassigned§modeling_task§
to§sheet1%n>add§basic_interaction%nadded§16:§basic_interaction%n>assign§16§2%nassigned§basic_interaction§to§sheet1%n>delete§16%ndeleted§basi
c_interaction§and§0§subtasks%n>delete§16%n!A!!R!^ERROR:§.*%n>assign§16§3%n!A!!R!^ERROR:§.*%n>restore§16%nrestored§basic_interaction§and§0§su
btasks%n>assign§16§3%nassigned§basic_interaction§to§sheet2%n>add§unsolvable_task%nadded§17:§unsolvable_task%n>assign§17§6%nassigned§unsolvab
le_task§to§sheet5%n>add§create_guide§2023-10-22%nadded§18:§create_guide%n>tag§18§complex%ntagged§create_guide§with§complex%n>before§2023-11-
10%n-§[§]§learn_java§[HI]:§-->§2023-09-30%n§§-§[x]§exceptions§[MD]%n§§§§-§[§]§don_use_as_lazy_shortcut%n§§-§[§]§streams§[MD]:§-->§2023-09-30
%n§§-§[§]§streams§[LO]%n-§[§]§learn_git§[HI]:§-->§2023-09-30%n-§[§]§sheet1:§-->§2023-11-05%n§§-§[§]§modeling_task%n-§[§]§create_guide:§(comp
lex)§-->§2023-10-22%n>add§write_solution%nadded§19:§write_solution%n>add-list§skills%nadded§skills%n>assign§11§skills%nassigned§command_patt
ern§to§skills%n>assign§12§skills%nassigned§error_handling§to§skills%n>assign§8§12%nassigned§exceptions§to§error_handling%n>list§skills%n-§[x
]§command_pattern%n-§[x]§error_handling%n§§-§[x]§exceptions§[MD]%n§§§§-§[§]§don_use_as_lazy_shortcut%n>delete§8%ndeleted§exceptions§and§1§su
btasks%n>list§skills%n-§[x]§command_pattern%n-§[x]§error_handling%n>find§l%n-§[§]§learn_java§[HI]:§-->§2023-09-30%n§§-§[§]§streams§[MD]:§-->
§2023-09-30%n§§-§[§]§streams§[LO]%n-§[§]§learn_git§[HI]:§-->§2023-09-30%n-§[§]§small_tasks%n§§-§[§]§sheet1:§-->§2023-11-05%n§§§§-§[§]§modeli
ng_task%n§§-§[§]§sheet2:§-->§2023-11-19%n§§§§-§[§]§basic_interaction%n§§-§[x]§sheet3:§-->§2023-12-03%n§§§§-§[x]§command_pattern%n§§-§[§]§she
et4:§-->§2023-12-17%n§§-§[§]§sheet5:§-->§2024-01-21%n§§§§-§[x]§error_handling%n§§§§-§[§]§unsolvable_task%n-§[§]§write_solution%n>toggle§12%n
toggled§error_handling§and§0§subtasks%n>restore§13%nrestored§don_use_as_lazy_shortcut§and§0§subtasks%n>restore§8%nrestored§exceptions§and§0§
subtasks%n>find§l%n-§[§]§learn_java§[HI]:§-->§2023-09-30%n§§-§[§]§streams§[MD]:§-->§2023-09-30%n§§-§[§]§streams§[LO]%n-§[§]§learn_git§[HI]:§
-->§2023-09-30%n-§[§]§small_tasks%n§§-§[§]§sheet1:§-->§2023-11-05%n§§§§-§[§]§modeling_task%n§§-§[§]§sheet2:§-->§2023-11-19%n§§§§-§[§]§basic_
interaction%n§§-§[x]§sheet3:§-->§2023-12-03%n§§§§-§[x]§command_pattern%n§§-§[§]§sheet4:§-->§2023-12-17%n§§-§[§]§sheet5:§-->§2024-01-21%n§§§§
-§[§]§error_handling%n§§§§§§-§[x]§exceptions§[MD]%n§§§§-§[§]§unsolvable_task%n-§[§]§write_solution%n-§[§]§don_use_as_lazy_shortcut%n>add§ref
actor%nadded§20:§refactor%n>assign§20§19%nassigned§refactor§to§write_solution%n>add§finalize%nadded§21:§finalize%n>assign§21§19%nassigned§fi
nalize§to§write_solution%n>add§refactor%nadded§22:§refactor%n>assign§22§21%nassigned§refactor§to§finalize%n>toggle§21%ntoggled§finalize§and§
1§subtasks%n>delete§20%ndeleted§refactor§and§0§subtasks%n>add§write_again_from_scratch_because_of_one_missed_detail_that_breaks_everything%n
added§23:§write_again_from_scratch_because_of_one_missed_detail_that_breaks_everything%n>assign§23§21%nassigned§write_again_from_scratch_bec
ause_of_one_missed_detail_that_breaks_everything§to§finalize%n>toggle§21%ntoggled§finalize§and§2§subtasks%n>change-priority§19§HI%nchanged§w
rite_solution§to§HI%n>find§l%n-§[§]§learn_java§[HI]:§-->§2023-09-30%n§§-§[§]§streams§[MD]:§-->§2023-09-30%n§§-§[§]§streams§[LO]%n-§[§]§learn
_git§[HI]:§-->§2023-09-30%n-§[§]§write_solution§[HI]%n§§-§[§]§finalize%n§§§§-§[§]§refactor%n§§§§-§[§]§write_again_from_scratch_because_of_on
e_missed_detail_that_breaks_everything%n-§[§]§small_tasks%n§§-§[§]§sheet1:§-->§2023-11-05%n§§§§-§[§]§modeling_task%n§§-§[§]§sheet2:§-->§2023
-11-19%n§§§§-§[§]§basic_interaction%n§§-§[x]§sheet3:§-->§2023-12-03%n§§§§-§[x]§command_pattern%n§§-§[§]§sheet4:§-->§2023-12-17%n§§-§[§]§shee
t5:§-->§2024-01-21%n§§§§-§[§]§error_handling%n§§§§§§-§[x]§exceptions§[MD]%n§§§§-§[§]§unsolvable_task%n-§[§]§don_use_as_lazy_shortcut%n>quit%
Tname:§FUNCTIONAL§Basic:§add-list%ncomment:§Tests§if§add-list§command§basically§behaves§as§expected,§no§prints%nargs:%n--%n>add-list§basicLi
st%nadded§basicList%n>add-list§basicList%n!A!!R!^ERROR:§.*%n>add-list§anotherList%nadded§anotherList%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLING
:§duplicates%ncomment:§Tests§if§the§parameters§are§parsed§correctly,§no§working§model§expected%nargs:%n--%n>duplicates§1%n!A!!R!^ERROR:§.*%n
>duplicates§task%n!A!!R!^ERROR:§.*%n>duplicates§2023-08-01%n!A!!R!^ERROR:§.*%n>duplicates%n!R!^(?!ERROR:§).*$%n>quit%Tname:§FUNCTIONAL§ERROR
§HANDLING:§add-list%ncomment:§Tests§if§the§parameters§are§parsed§correctly,§no§working§model§expected%nargs:%n--%n>add-list%n!A!!R!^ERROR:§.
*%n>add-list§1stList%n!A!!R!^ERROR:§.*%n>add-list§my_list%n!A!!R!^ERROR:§.*%n>add-list§my§list%n!A!!R!^ERROR:§.*%n>add-list§w§w%n!A!!R!^ERRO
R:§.*%n>add-list§aList%n!R!^(?!ERROR:§).*$%n>quit%Tname:§FUNCTIONAL§Mixed:§delete%ncomment:§Tests§if§delete§command§basically§behaves§as§exp
ected%nargs:%n--%n#setup%n>add§ticket%nadded§1:§ticket%n>add§suitcase%nadded§2:§suitcase%n>add§snacks%nadded§3:§snacks%n>add§suncream%nadded
§4:§suncream%n>add§sunglasses%nadded§5:§sunglasses%n>add§passport%nadded§6:§passport%n>add§money%nadded§7:§money%n>add§phone%nadded§8:§phone
%n>add-list§travel%nadded§travel%n>add-list§work%nadded§work%n>assign§2§travel%nassigned§suitcase§to§travel%n>list§travel%n-§[§]§suitcase%n>
delete§2%ndeleted§suitcase§and§0§subtasks#§§§§§§§§§§§top§level§without§subtasks%n>delete§2%n!A!!R!^ERROR:§.*%n>list§travel%n>assign§7§8%nass
igned§money§to§phone%n>assign§8§work%nassigned§phone§to§work%n>list§work%n-§[§]§phone%n§§-§[§]§money%n>delete§7%ndeleted§money§and§0§subtask
s#§§§§§§§§§§§§§§subtask§without§subtasks%n>delete§7%n!A!!R!^ERROR:§.*%n>list§work%n-§[§]§phone%n>assign§6§8%nassigned§passport§to§phone%n>as
sign§3§8%nassigned§snacks§to§phone%n>list§work%n-§[§]§phone%n§§-§[§]§passport%n§§-§[§]§snacks%n>delete§8%ndeleted§phone§and§2§subtasks#§§§§§
§§§§§§§§§top§level§with§subtasks%n>delete§8%n!A!!R!^ERROR:§.*%n>delete§3%n!A!!R!^ERROR:§.*%n>delete§6%n!A!!R!^ERROR:§.*%n>assign§5§4%nassign
ed§sunglasses§to§suncream%n>assign§4§1%nassigned§suncream§to§ticket%n>assign§1§travel%nassigned§ticket§to§travel%n>list§travel%n-§[§]§ticket
%n§§-§[§]§suncream%n§§§§-§[§]§sunglasses%n>delete§4%ndeleted§suncream§and§1§subtasks#§§§§§§§§§§§subtask§with§subtasks%n>delete§4%n!A!!R!^ERR
OR:§.*%n>delete§5%n!A!!R!^ERROR:§.*%n>list§travel%n-§[§]§ticket%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLING:§todo%ncomment:§Tests§if§the§paramet
ers§are§parsed§correctly,§no§working§model§expected%nargs:%n--%n>todo§1%n!A!!R!^ERROR:§.*%n>todo%n!R!^(?!ERROR:§).*$%n>quit%Tname:§FUNCTIONA
L§Basic:§delete§for§tasks%ncomment:§Tests§if§delete§command§basically§behaves§as§expected§for§tasks,§lists§ignored%nargs:%n--%n#setup%n>add§
sweets%nadded§1:§sweets%n>add§nimm2%nadded§2:§nimm2%n>add§toffifee%nadded§3:§toffifee%n>add§chocolate%nadded§4:§chocolate%n>add§toblerone%na
dded§5:§toblerone%n>add§salad%nadded§6:§salad%n>add§bonbon%nadded§7:§bonbon%n>add§marshmallows%nadded§8:§marshmallows%n>assign§3§4%nassigned
§toffifee§to§chocolate%n>assign§5§4%nassigned§toblerone§to§chocolate%n>assign§4§1%nassigned§chocolate§to§sweets%n>assign§2§7%nassigned§nimm2
§to§bonbon%n>assign§7§1%nassigned§bonbon§to§sweets%n>assign§8§1%nassigned§marshmallows§to§sweets%n#%n#%n#§§§§§§§salad§§§§§§§§§§§§§§§§§§§§§§§
§sweets%n#§§§§§§§§§§§§§§§§§§§§§§§§§§§§§/§§§§§§§§|§§§§§§§§§\\%n#§§§§§§§§§§§§§§§§§§§§§§bonbon§§§§§§chocolate§§§§§§§marshmallows%n#§§§§§§§§§§§§
§§§§§§§§§§/§§§§§§§§§§§§§/§§§§\\%n#§§§§§§§§§§§§§§§§§§§nimm2§§§§§§§toffifee§§toblerone%n#%n#%n>delete§6%ndeleted§salad§and§0§subtasks#§§§§§§§§
§§delete§top§level§without§subtasks%n>delete§6%n!A!!R!^ERROR:§.*%n>delete§8%ndeleted§marshmallows§and§0§subtasks#§§§delete§subtask§without§s
ubtasks%n>delete§8%n!A!!R!^ERROR:§.*%n>delete§7%ndeleted§bonbon§and§1§subtasks#§§§§§§§§§delete§subtask§with§subtasks%n>delete§7%n!A!!R!^ERRO
R:§.*%n>delete§2%n!A!!R!^ERROR:§.*%n>delete§1%ndeleted§sweets§and§3§subtasks#§§§§§§§§§delete§top§level§with§subtasks%n>delete§1%n!A!!R!^ERRO
R:§.*%n>delete§3%n!A!!R!^ERROR:§.*%n>delete§4%n!A!!R!^ERROR:§.*%n>delete§5%n!A!!R!^ERROR:§.*%n#%n#%n#%n#misc%n>restore§6%nrestored§salad§and
§0§subtasks%n>delete§6%ndeleted§salad§and§0§subtasks#§§§§§§§§§§redelete%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLING:§delete%ncomment:§Tests§if§t
he§parameters§are§parsed§correctly,§no§working§model§expected%nargs:%n--%n>add§task%n!R!^(?!ERROR:§).*$%n>delete%n!A!!R!^ERROR:§.*%n>delete§
1§1%n!A!!R!^ERROR:§.*%n>delete§task%n!A!!R!^ERROR:§.*%n>delete§1%n!R!^(?!ERROR:§).*$%n>quit%Tname:§FUNCTIONAL§Basic:§toggle%ncomment:§Tests§
if§toggle§command§basically§behaves§as§expected%nargs:%n--%n#setup%n>add§black%nadded§1:§black%n>add§grey%nadded§2:§grey%n>add§white%nadded§
3:§white%n>assign§2§1%nassigned§grey§to§black%n#%n#%n#%n#test§toggle%n>toggle§3%ntoggled§white§and§0§subtasks#§§§§§§§basic§toggle§(->§marked
)%n>toggle§3%ntoggled§white§and§0§subtasks#§§§§§§§basic§toggle§(->§unmarked)%n>toggle§1%ntoggled§black§and§1§subtasks#§§§§§§§toggle§with§sub
task§(top§->§marked,§sub§->§marked)%n>toggle§2%ntoggled§grey§and§0§subtasks#§§§§§§§§toggle§subtask§(->§unmarked)%n>toggle§1%ntoggled§black§a
nd§1§subtasks#§§§§§§§toggle§with§subtask§(top§->§unmarked,§sub§->§marked)%n>toggle§1%ntoggled§black§and§1§subtasks#§§§§§§§toggle§with§subtas
k§(top§->§marked,§sub§->§unmarked)%n>toggle§2%ntoggled§grey§and§0§subtasks#§§§§§§§§toggle§subtask§(->§marked)%n>toggle§1%ntoggled§black§and§
1§subtasks#§§§§§§§toggle§with§subtask§(top§->§unmarked,§sub§->§unmarked)%n#%n#%n#%n#misc%n>toggle§3%ntoggled§white§and§0§subtasks#§§§§§§§(->
§marked)%n>assign§3§2%nassigned§white§to§grey%n>toggle§1%ntoggled§black§and§2§subtasks#§§§§§§§toggle§with§multiple§subtasks§(top§->§marked,§
sub§->§marked,§subsub§->§unmarked)%n>toggle§4%n!A!!R!^ERROR:§.*%n>delete§3%ndeleted§white§and§0§subtasks%n>toggle§3%n!A!!R!^ERROR:§.*%n>rest
ore§3%nrestored§white§and§0§subtasks%n>toggle§3%ntoggled§white§and§0§subtasks%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLING:§toggle%ncomment:§Test
s§if§the§parameters§are§parsed§correctly,§no§working§model§expected%nargs:%n--%n>add§task%n!R!^(?!ERROR:§).*$%n>toggle%n!A!!R!^ERROR:§.*%n>t
oggle§1§whatever%n!A!!R!^ERROR:§.*%n>toggle§1§1%n!A!!R!^ERROR:§.*%n>toggle§task%n!A!!R!^ERROR:§.*%n>toggle§1%n!R!^(?!ERROR:§).*$%n>quit%Tnam
e:§FUNCTIONAL§ERROR§HANDLING:§add%ncomment:§Tests§if§the§parameters§are§parsed§correctly,§no§working§model§expected%nargs:%n--%n>add%n!A!!R!
^ERROR:§.*%n>add§name§space%n!A!!R!^ERROR:§.*%n>add§name§space§HI%n!A!!R!^ERROR:§.*%n>add§name§space§MD§2023-06-25%n!A!!R!^ERROR:§.*%n>add§s
yntax_name%n!R!^(?!ERROR:§).*$%n>add§syntax_prio§HI%n!R!^(?!ERROR:§).*$%n>add§syntax_date§2023-07-31%n!R!^(?!ERROR:§).*$%n>add§syntax_all§LO
§2023-07-30%n!R!^(?!ERROR:§).*$%n>add§syntax_more§HI§2023-07-30§HI%n!A!!R!^ERROR:§.*%n>add§syntax_more§HI§2023-07-30§HI§2023-07-30%n!A!!R!^E
RROR:§.*%n>add§syntax_swapped§2023-07-30§HI%n!A!!R!^ERROR:§.*%n>add§double_date;)§2023-07-30§2023-07-30%n!A!!R!^ERROR:§.*%n>add§double_top§H
I§HI%n!A!!R!^ERROR:§.*%n>add§double_mid§MD§MD%n!A!!R!^ERROR:§.*%n>add§double_bot§LO§LO%n!A!!R!^ERROR:§.*%n>add§bounds§2023-05-32%n!A!!R!^ERR
OR:§.*%n>add§bounds§MD§2023-11-00%n!A!!R!^ERROR:§.*%n>add§bounds§2023-00-02%n!A!!R!^ERROR:§.*%n>add§bounds§MD§2023-13-02%n!A!!R!^ERROR:§.*%n
>add§2023-08-01%n!R!^(?!ERROR:§).*$%n>add§HI%n!R!^(?!ERROR:§).*$%n>add§HI§HI%n!R!^(?!ERROR:§).*$%n>add§MD%n!R!^(?!ERROR:§).*$%n>add§LO%n!R!^
(?!ERROR:§).*$%n>add§2023-08-02§2023-08-02%n!R!^(?!ERROR:§).*$%n>add§max_date§9999-12-31%n!R!^(?!ERROR:§).*$%n>add§year_zero§0000-01-01%n!R!
^(?!ERROR:§).*$%n>add§leap_year§2016-02-29%n!R!^(?!ERROR:§).*$%n>quit%Tname:§FUNCTIONAL§Basic:§add%ncomment:§Tests§if§add§command§basically§
behaves§as§expected,§no§prints%nargs:%n--%n>add§basic%nadded§1:§basic%n>add§basic%nadded§2:§basic%n>add§otherBasic%nadded§3:§otherBasic%n>ad
d§prio-high§HI%nadded§4:§prio-high%n>add§prio-high§HI%nadded§5:§prio-high%n>add§otherPrio-high§HI%nadded§6:§otherPrio-high%n>add§prio-mid§MD
%nadded§7:§prio-mid%n>add§prio-mid§MD%nadded§8:§prio-mid%n>add§otherPrio-mid§MD%nadded§9:§otherPrio-mid%n>add§prio-low§LO%nadded§10:§prio-lo
w%n>add§prio-low§LO%nadded§11:§prio-low%n>add§otherPrio-low§LO%nadded§12:§otherPrio-low%n>add§date§2023-06-23%nadded§13:§date%n>add§date§202
3-06-23%nadded§14:§date%n>add§otherDate§2023-06-23%nadded§15:§otherDate%n>add§high-date§HI§2020-04-01%nadded§16:§high-date%n>add§high-date§H
I§2020-04-01%nadded§17:§high-date%n>add§otherHigh-date§HI§2020-04-01%nadded§18:§otherHigh-date%n>quit%Tname:§FUNCTIONAL§ERROR§HANDLING:§find
%ncomment:§Tests§if§the§parameters§are§parsed§correctly,§no§working§model§expected%nargs:%n--%n>find%n!A!!R!^ERROR:§.*%n>find§name§name%n!A!
!R!^ERROR:§.*%n>find§name%n!R!^(?!ERROR:§).*$%n>quit
            """;

    private Testcases() {
    }
}
